//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MundlTransit.WP8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MundlTransit.WP8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app uses open data provided by Wiener Linien. To learn more about the data and API they are offering, please visit.
        /// </summary>
        public static string About_InfoParagraphOne {
            get {
                return ResourceManager.GetString("About_InfoParagraphOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No personally identifyable information (including location data) is sent by this app..
        /// </summary>
        public static string About_InfoParagraphTwo {
            get {
                return ResourceManager.GetString("About_InfoParagraphTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About_PageTitle {
            get {
                return ResourceManager.GetString("About_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string About_PrivacyPolicy_LinkText {
            get {
                return ResourceManager.GetString("About_PrivacyPolicy_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review this app.
        /// </summary>
        public static string About_ReviewApp_ButtonText {
            get {
                return ResourceManager.GetString("About_ReviewApp_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support and Source Code.
        /// </summary>
        public static string About_SupportSourceCode_LinkText {
            get {
                return ResourceManager.GetString("About_SupportSourceCode_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string About_Version_Text {
            get {
                return ResourceManager.GetString("About_Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorMessage_Title {
            get {
                return ResourceManager.GetString("ErrorMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any favorites yet..
        /// </summary>
        public static string Favorites_NoFavoritesYet {
            get {
                return ResourceManager.GetString("Favorites_NoFavoritesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string Favorites_PageTitle {
            get {
                return ResourceManager.GetString("Favorites_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direction.
        /// </summary>
        public static string LineInfo_AppBar_Direction {
            get {
                return ResourceManager.GetString("LineInfo_AppBar_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bus.
        /// </summary>
        public static string Lines_Bus {
            get {
                return ResourceManager.GetString("Lines_Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metro.
        /// </summary>
        public static string Lines_Metro {
            get {
                return ResourceManager.GetString("Lines_Metro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to night bus.
        /// </summary>
        public static string Lines_NightBus {
            get {
                return ResourceManager.GetString("Lines_NightBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        public static string Lines_PageTitle {
            get {
                return ResourceManager.GetString("Lines_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tram.
        /// </summary>
        public static string Lines_Tram {
            get {
                return ResourceManager.GetString("Lines_Tram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu.
        /// </summary>
        public static string Menu_PageTitle {
            get {
                return ResourceManager.GetString("Menu_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MenuItem_About {
            get {
                return ResourceManager.GetString("MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy policy, support.
        /// </summary>
        public static string MenuItem_About_Description {
            get {
                return ResourceManager.GetString("MenuItem_About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearby.
        /// </summary>
        public static string MenuItem_Nearby {
            get {
                return ResourceManager.GetString("MenuItem_Nearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stations nearby your current location.
        /// </summary>
        public static string MenuItem_Nearby_Description {
            get {
                return ResourceManager.GetString("MenuItem_Nearby_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string MenuItem_Search {
            get {
                return ResourceManager.GetString("MenuItem_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stations by name (fulltext).
        /// </summary>
        public static string MenuItem_Search_Description {
            get {
                return ResourceManager.GetString("MenuItem_Search_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MenuItem_Settings {
            get {
                return ResourceManager.GetString("MenuItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn on/off geolocation for nearby search.
        /// </summary>
        public static string MenuItem_Settings_Description {
            get {
                return ResourceManager.GetString("MenuItem_Settings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to station list.
        /// </summary>
        public static string MenuItem_StationList {
            get {
                return ResourceManager.GetString("MenuItem_StationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete list of stations.
        /// </summary>
        public static string MenuItem_StationList_Description {
            get {
                return ResourceManager.GetString("MenuItem_StationList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stations by lines.
        /// </summary>
        public static string MenuItem_StationsByLines {
            get {
                return ResourceManager.GetString("MenuItem_StationsByLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metro, tram and buses by direction.
        /// </summary>
        public static string MenuItem_StationsByLines_Description {
            get {
                return ResourceManager.GetString("MenuItem_StationsByLines_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorite added.
        /// </summary>
        public static string Message_FavoriteAdded {
            get {
                return ResourceManager.GetString("Message_FavoriteAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading departure information failed..
        /// </summary>
        public static string MonitorError_DownloadingFailed {
            get {
                return ResourceManager.GetString("MonitorError_DownloadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No departure information was sent by the server..
        /// </summary>
        public static string MonitorError_FallbackOnErrorToErrorMessageConversion {
            get {
                return ResourceManager.GetString("MonitorError_FallbackOnErrorToErrorMessageConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured, please try again later..
        /// </summary>
        public static string MonitorError_GenericError {
            get {
                return ResourceManager.GetString("MonitorError_GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No departures available at this time..
        /// </summary>
        public static string MonitorError_MonitorsEmpty {
            get {
                return ResourceManager.GetString("MonitorError_MonitorsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal app error: RBL not specified..
        /// </summary>
        public static string MonitorError_RblNotSpecified {
            get {
                return ResourceManager.GetString("MonitorError_RblNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the response failed..
        /// </summary>
        public static string MonitorError_ResponseParsingFailed {
            get {
                return ResourceManager.GetString("MonitorError_ResponseParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app has failed to authenticate to the Wiener Linien API..
        /// </summary>
        public static string MonitorError_ServerAuthenticationFailed {
            get {
                return ResourceManager.GetString("MonitorError_ServerAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app has exceeded the call quota allowed by Wiener Linien..
        /// </summary>
        public static string MonitorError_ServerCallQuotaExceeded {
            get {
                return ResourceManager.GetString("MonitorError_ServerCallQuotaExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error reported: Database unavailable..
        /// </summary>
        public static string MonitorError_ServerDatabaseUnavailable {
            get {
                return ResourceManager.GetString("MonitorError_ServerDatabaseUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error reported: No data in database..
        /// </summary>
        public static string MonitorError_ServerNoDataInDatabase {
            get {
                return ResourceManager.GetString("MonitorError_ServerNoDataInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app has failed to send a properly formatted query to the Wiener Linien API..
        /// </summary>
        public static string MonitorError_ServerQueryStringParameterInvalid {
            get {
                return ResourceManager.GetString("MonitorError_ServerQueryStringParameterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stop does not exist (stop database out of date?)..
        /// </summary>
        public static string MonitorError_ServerStopDoesNotExist {
            get {
                return ResourceManager.GetString("MonitorError_ServerStopDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stops found near.
        /// </summary>
        public static string PositionMessage_NoStopsFoundNear {
            get {
                return ResourceManager.GetString("PositionMessage_NoStopsFoundNear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your position.
        /// </summary>
        public static string PositionMessage_YourPosition {
            get {
                return ResourceManager.GetString("PositionMessage_YourPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquiring position....
        /// </summary>
        public static string ProgressMessage_AcquiringPosition {
            get {
                return ResourceManager.GetString("ProgressMessage_AcquiringPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading departures....
        /// </summary>
        public static string ProgressMessage_LoadingDepartures {
            get {
                return ResourceManager.GetString("ProgressMessage_LoadingDepartures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geolocation for nearby stations.
        /// </summary>
        public static string Settings_GeolocationForNearbyStations {
            get {
                return ResourceManager.GetString("Settings_GeolocationForNearbyStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings_PageTitle {
            get {
                return ResourceManager.GetString("Settings_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorite.
        /// </summary>
        public static string StationInfo_AppBar_Favorite {
            get {
                return ResourceManager.GetString("StationInfo_AppBar_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string StationInfo_AppBar_Refresh {
            get {
                return ResourceManager.GetString("StationInfo_AppBar_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to walk to.
        /// </summary>
        public static string StationInfo_AppBar_WalkTo {
            get {
                return ResourceManager.GetString("StationInfo_AppBar_WalkTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to departures.
        /// </summary>
        public static string StationInfo_Departures_Title {
            get {
                return ResourceManager.GetString("StationInfo_Departures_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        public static string Stations_AppBar_Map {
            get {
                return ResourceManager.GetString("Stations_AppBar_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string Stations_AppBar_Refresh {
            get {
                return ResourceManager.GetString("Stations_AppBar_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        public static string Stations_ListTitle {
            get {
                return ResourceManager.GetString("Stations_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearby.
        /// </summary>
        public static string Stations_NearbyTitle {
            get {
                return ResourceManager.GetString("Stations_NearbyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations.
        /// </summary>
        public static string Stations_PageTitle {
            get {
                return ResourceManager.GetString("Stations_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Stations_SearchTitle {
            get {
                return ResourceManager.GetString("Stations_SearchTitle", resourceCulture);
            }
        }
    }
}
